### ISSUE TITLE
negative relative humidity?

### ISSUE THREAD

**Issue by mountain** [pangeo-data/WeatherBench#18]
Hi, maintainer,

I checked with the value range of relative humidity, but found some negitive values.
Are these cases abnormal? Should I filter them out?

```ipython
In [1]: import xarray as xr                                                                                                                         

In [2]: ds = xr.open_dataset('/data/weather_bench/relative_humidity/relative_humidity_1979_5.625deg.nc')                               

In [3]: ds.r.max()                                                                                                                                  
Out[3]: 
<xarray.DataArray 'r' ()>
array(195.39139, dtype=float32)

In [4]: ds.r.min()                                                                                                                                  
Out[4]: 
<xarray.DataArray 'r' ()>
array(-9.228312, dtype=float32)
```

These situations are persistent among all the years.

**Comment by raspstephan** [comment]
Thanks for spotting this. 

I just confirmed this. There seem to be quite a few negative values. At this stage I have no good answer why this is the case. My initial solution for this would be to set negative values to zero. 

I have mostly been using specific humidity instead, which should give similar results.

BTW, RH values above 100% are realistic because of super-saturation.

**Comment by mountain** [comment]
Thanks for the response. We are setting up models by the data, Weather Bench is very helpful.
